### ISSUE TITLE
Tracker: Features, Bugs and Documentation

### ISSUE THREAD

**Issue by musamarcusso** [uuvsimulator/uuv_simulator#365]
Hello everyone, 

I am trying to make a list of the all the features/bugs/documentation tasks that need to be finished soon, so I am creating this issue tracker here that I will be updating and listing so I can have a better overview. Please, feel free to add a comment on what you any improvements or fixes you think are most important for you and your project, it will help a lot. All contributions are most welcome :)

# [Documentation](https://uuvsimulator.github.io/packages/uuv_simulator/intro/)

- [ ] Add page to `Features` on the thruster models available 
- [ ] Add page to `Features` on the fin models available
- [ ] Add page to `Features` on the world plugins for current velocity
- [ ] Add page to `Features` on the controllers available
- [ ] Add page to `Features` on the local path planners and trajectory generators
- [ ] Add page to `Features` on how to use the NED frame
- [ ] Add page to `User Guide` on how to write a fin snippet to add in the URDF file.
- [ ] Add page to `User Guide` on how to write the URDF snippet for the hydrodynamic model for a vehicle
- [ ] Add page to `User Guide` on how to write the `robot_description` URDF file for a USV
- [ ] Add page to `User Guide` on how to write a thruster snippet to add in the URDF file.
- [ ] Add page to `User Guide` on how to write snippets for the available sensors.

# Features

- [ ] Add configurable wave shaders based on models as JONSWAP, PM
- [ ] Add plugin to compute wave loads #309 #313 
- [ ] Add keyboard teleop configuration #354 
- [ ] Use jinja for the generation of the package templates (robot description, thruster manager configuration)
- [ ] Add specific underwater shaders to avoid Gazebo's fog simulation that spreads over the whole scenario
- [ ] Add umbilical load plugin for ROVs
- [ ] Add the models and worlds to the [marketplace](https://app.ignitionrobotics.org/fuel/models)

# Bugs

- [ ] Fix the GPS sensor plugin (use libgeographic for conversions)
- [ ] Fix sand material #340  
- [ ] Fix the hydrodynamic model for ellipsoids
- [ ] Improve all the Gazebo models (mainly textures)
- [ ] Fix the [Oberon manipulators](https://github.com/uuvsimulator/uuv_manipulators) to run again in combination with the RexROV

**Comment by Emma365** [comment]
More information/documentation about integrating sensors (such as DVL and GPS) would be very useful
